[package]
name = "user_crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
type_crate = { path = "../type_crate" }
trait_crate = { path = "../trait_crate" }
